namespace: llkhe

msa:
  enabled: true
  image: "ms-a:latest"
  imagePullPolicy: Never
  port: 8181
  nodePort: 30181
  kafkaServers: "kafka-1"
  kafkaPort: 29092
  kafkaTopic: "person-events"
  redisHost: "redis"
  redisPort: 6379



msb:
  enabled: true
  image: "ms-b:latest"
  imagePullPolicy: Never
  port: 8181
  kafkaServers: "kafka-1"
  kafkaPort: 29092
  kafkaTopic: "person-events"
  kafkaGroup: "person-ms-b"
  redisHost: "redis"
  redisPort: 6379

