{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafka.broker.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.kafka.broker.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.kafka.broker.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.broker.name }}
    spec:
      hostname: {{ .Values.kafka.broker.name }}
      initContainers:
      - name: wait-for-zookeeper
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -vz {{ .Values.zookeeper.name }} 2181; do echo "Waiting for Zookeeper..."; sleep 2; done;']
      containers:
      - name: kafka
        image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
        ports:
        - containerPort: {{ .Values.kafka.ports.external }}
        - containerPort: {{ .Values.kafka.ports.internal }}
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "{{ .Values.zookeeper.name }}:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://{{ .Values.kafka.broker.name }}:{{ .Values.kafka.ports.internal }},PLAINTEXT_HOST://{{ .Values.kafka.broker.name }}:{{ .Values.kafka.ports.external }}"
        - name: KAFKA_BROKER_ID
          value: {{ .Values.kafka.broker.id | quote }}
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
{{- end }}

